# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection_domain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fraud_detection_domain.proto',
  package='frauddetection.domain',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x66raud_detection_domain.proto\x12\x15\x66rauddetection.domain\"W\n\x15\x46raudDetectionCreated\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x18\n\x10max_amount_cents\x18\x03 \x01(\x05\"\xac\x01\n\x16ScoredTransactionAdded\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x14\n\x0c\x61mount_cents\x18\x04 \x01(\x05\x12\x17\n\x0fpotential_fraud\x18\x05 \x01(\x08\x12\x12\n\nrisk_score\x18\x06 \x01(\x05\x12\x0f\n\x07rule_id\x18\x07 \x01(\t\"Z\n\x19\x46raudDetectionRuleUpdated\x12\x12\n\ncustomerId\x18\x01 \x01(\t\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x18\n\x10max_amount_cents\x18\x03 \x01(\x05\x62\x06proto3'
)




_FRAUDDETECTIONCREATED = _descriptor.Descriptor(
  name='FraudDetectionCreated',
  full_name='frauddetection.domain.FraudDetectionCreated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='frauddetection.domain.FraudDetectionCreated.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rule_id', full_name='frauddetection.domain.FraudDetectionCreated.rule_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_amount_cents', full_name='frauddetection.domain.FraudDetectionCreated.max_amount_cents', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=142,
)


_SCOREDTRANSACTIONADDED = _descriptor.Descriptor(
  name='ScoredTransactionAdded',
  full_name='frauddetection.domain.ScoredTransactionAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='frauddetection.domain.ScoredTransactionAdded.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='frauddetection.domain.ScoredTransactionAdded.transaction_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='frauddetection.domain.ScoredTransactionAdded.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount_cents', full_name='frauddetection.domain.ScoredTransactionAdded.amount_cents', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='potential_fraud', full_name='frauddetection.domain.ScoredTransactionAdded.potential_fraud', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='risk_score', full_name='frauddetection.domain.ScoredTransactionAdded.risk_score', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rule_id', full_name='frauddetection.domain.ScoredTransactionAdded.rule_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=317,
)


_FRAUDDETECTIONRULEUPDATED = _descriptor.Descriptor(
  name='FraudDetectionRuleUpdated',
  full_name='frauddetection.domain.FraudDetectionRuleUpdated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerId', full_name='frauddetection.domain.FraudDetectionRuleUpdated.customerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rule_id', full_name='frauddetection.domain.FraudDetectionRuleUpdated.rule_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_amount_cents', full_name='frauddetection.domain.FraudDetectionRuleUpdated.max_amount_cents', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=409,
)

DESCRIPTOR.message_types_by_name['FraudDetectionCreated'] = _FRAUDDETECTIONCREATED
DESCRIPTOR.message_types_by_name['ScoredTransactionAdded'] = _SCOREDTRANSACTIONADDED
DESCRIPTOR.message_types_by_name['FraudDetectionRuleUpdated'] = _FRAUDDETECTIONRULEUPDATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FraudDetectionCreated = _reflection.GeneratedProtocolMessageType('FraudDetectionCreated', (_message.Message,), {
  'DESCRIPTOR' : _FRAUDDETECTIONCREATED,
  '__module__' : 'fraud_detection_domain_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.domain.FraudDetectionCreated)
  })
_sym_db.RegisterMessage(FraudDetectionCreated)

ScoredTransactionAdded = _reflection.GeneratedProtocolMessageType('ScoredTransactionAdded', (_message.Message,), {
  'DESCRIPTOR' : _SCOREDTRANSACTIONADDED,
  '__module__' : 'fraud_detection_domain_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.domain.ScoredTransactionAdded)
  })
_sym_db.RegisterMessage(ScoredTransactionAdded)

FraudDetectionRuleUpdated = _reflection.GeneratedProtocolMessageType('FraudDetectionRuleUpdated', (_message.Message,), {
  'DESCRIPTOR' : _FRAUDDETECTIONRULEUPDATED,
  '__module__' : 'fraud_detection_domain_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.domain.FraudDetectionRuleUpdated)
  })
_sym_db.RegisterMessage(FraudDetectionRuleUpdated)


# @@protoc_insertion_point(module_scope)
