# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from cloudstate import entity_key_pb2 as cloudstate_dot_entity__key__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import fraud_detection_common_pb2 as fraud__detection__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fraud_detection_service.proto',
  package='frauddetection',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x66raud_detection_service.proto\x12\x0e\x66rauddetection\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1b\x63loudstate/entity_key.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1c\x66raud_detection_common.proto\"c\n\x1b\x43reateFraudDetectionCommand\x12\x19\n\x0b\x63ustomer_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x18\n\x10max_amount_cents\x18\x03 \x01(\x05\"s\n\x15\x41\x64\x64TransactionCommand\x12\x19\n\x0b\x63ustomer_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x14\n\x0c\x61mount_cents\x18\x04 \x01(\x05\"5\n\x18GetFraudDetectionCommand\x12\x19\n\x0b\x63ustomer_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\"g\n\x1fUpdateFraudDetectionRuleCommand\x12\x19\n\x0b\x63ustomer_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x18\n\x10max_amount_cents\x18\x03 \x01(\x05\x32\xdf\x04\n\x15\x46raudDetectionService\x12\x8f\x01\n\x14\x43reateFraudDetection\x12+.frauddetection.CreateFraudDetectionCommand\x1a\x16.google.protobuf.Empty\"2\x82\xd3\xe4\x93\x02,\"\'/fraud-detection/create-fraud-detection:\x01*\x12\x97\x01\n\x18UpdateFraudDetectionRule\x12/.frauddetection.UpdateFraudDetectionRuleCommand\x1a\x16.google.protobuf.Empty\"2\x82\xd3\xe4\x93\x02,\"\'/fraud-detection/update-fraud-detection:\x01*\x12\x8c\x01\n\x0e\x41\x64\x64Transaction\x12%.frauddetection.AddTransactionCommand\x1a&.frauddetection.ScoredTransactionState\"+\x82\xd3\xe4\x93\x02%\" /fraud-detection/add-transaction:\x01*\x12\x8a\x01\n\x11GetFraudDetection\x12(.frauddetection.GetFraudDetectionCommand\x1a#.frauddetection.FraudDetectionState\"&\x82\xd3\xe4\x93\x02 \x12\x1e/fraud-detection/{customer_id}b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,cloudstate_dot_entity__key__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,fraud__detection__common__pb2.DESCRIPTOR,])




_CREATEFRAUDDETECTIONCOMMAND = _descriptor.Descriptor(
  name='CreateFraudDetectionCommand',
  full_name='frauddetection.CreateFraudDetectionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='frauddetection.CreateFraudDetectionCommand.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220\265\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rule_id', full_name='frauddetection.CreateFraudDetectionCommand.rule_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_amount_cents', full_name='frauddetection.CreateFraudDetectionCommand.max_amount_cents', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=266,
)


_ADDTRANSACTIONCOMMAND = _descriptor.Descriptor(
  name='AddTransactionCommand',
  full_name='frauddetection.AddTransactionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='frauddetection.AddTransactionCommand.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220\265\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='frauddetection.AddTransactionCommand.transaction_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='frauddetection.AddTransactionCommand.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount_cents', full_name='frauddetection.AddTransactionCommand.amount_cents', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=383,
)


_GETFRAUDDETECTIONCOMMAND = _descriptor.Descriptor(
  name='GetFraudDetectionCommand',
  full_name='frauddetection.GetFraudDetectionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='frauddetection.GetFraudDetectionCommand.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220\265\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=438,
)


_UPDATEFRAUDDETECTIONRULECOMMAND = _descriptor.Descriptor(
  name='UpdateFraudDetectionRuleCommand',
  full_name='frauddetection.UpdateFraudDetectionRuleCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='frauddetection.UpdateFraudDetectionRuleCommand.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220\265\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rule_id', full_name='frauddetection.UpdateFraudDetectionRuleCommand.rule_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_amount_cents', full_name='frauddetection.UpdateFraudDetectionRuleCommand.max_amount_cents', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=543,
)

DESCRIPTOR.message_types_by_name['CreateFraudDetectionCommand'] = _CREATEFRAUDDETECTIONCOMMAND
DESCRIPTOR.message_types_by_name['AddTransactionCommand'] = _ADDTRANSACTIONCOMMAND
DESCRIPTOR.message_types_by_name['GetFraudDetectionCommand'] = _GETFRAUDDETECTIONCOMMAND
DESCRIPTOR.message_types_by_name['UpdateFraudDetectionRuleCommand'] = _UPDATEFRAUDDETECTIONRULECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateFraudDetectionCommand = _reflection.GeneratedProtocolMessageType('CreateFraudDetectionCommand', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFRAUDDETECTIONCOMMAND,
  '__module__' : 'fraud_detection_service_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.CreateFraudDetectionCommand)
  })
_sym_db.RegisterMessage(CreateFraudDetectionCommand)

AddTransactionCommand = _reflection.GeneratedProtocolMessageType('AddTransactionCommand', (_message.Message,), {
  'DESCRIPTOR' : _ADDTRANSACTIONCOMMAND,
  '__module__' : 'fraud_detection_service_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.AddTransactionCommand)
  })
_sym_db.RegisterMessage(AddTransactionCommand)

GetFraudDetectionCommand = _reflection.GeneratedProtocolMessageType('GetFraudDetectionCommand', (_message.Message,), {
  'DESCRIPTOR' : _GETFRAUDDETECTIONCOMMAND,
  '__module__' : 'fraud_detection_service_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.GetFraudDetectionCommand)
  })
_sym_db.RegisterMessage(GetFraudDetectionCommand)

UpdateFraudDetectionRuleCommand = _reflection.GeneratedProtocolMessageType('UpdateFraudDetectionRuleCommand', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEFRAUDDETECTIONRULECOMMAND,
  '__module__' : 'fraud_detection_service_pb2'
  # @@protoc_insertion_point(class_scope:frauddetection.UpdateFraudDetectionRuleCommand)
  })
_sym_db.RegisterMessage(UpdateFraudDetectionRuleCommand)


_CREATEFRAUDDETECTIONCOMMAND.fields_by_name['customer_id']._options = None
_ADDTRANSACTIONCOMMAND.fields_by_name['customer_id']._options = None
_GETFRAUDDETECTIONCOMMAND.fields_by_name['customer_id']._options = None
_UPDATEFRAUDDETECTIONRULECOMMAND.fields_by_name['customer_id']._options = None

_FRAUDDETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='FraudDetectionService',
  full_name='frauddetection.FraudDetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=546,
  serialized_end=1153,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateFraudDetection',
    full_name='frauddetection.FraudDetectionService.CreateFraudDetection',
    index=0,
    containing_service=None,
    input_type=_CREATEFRAUDDETECTIONCOMMAND,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=b'\202\323\344\223\002,\"\'/fraud-detection/create-fraud-detection:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFraudDetectionRule',
    full_name='frauddetection.FraudDetectionService.UpdateFraudDetectionRule',
    index=1,
    containing_service=None,
    input_type=_UPDATEFRAUDDETECTIONRULECOMMAND,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=b'\202\323\344\223\002,\"\'/fraud-detection/update-fraud-detection:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddTransaction',
    full_name='frauddetection.FraudDetectionService.AddTransaction',
    index=2,
    containing_service=None,
    input_type=_ADDTRANSACTIONCOMMAND,
    output_type=fraud__detection__common__pb2._SCOREDTRANSACTIONSTATE,
    serialized_options=b'\202\323\344\223\002%\" /fraud-detection/add-transaction:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFraudDetection',
    full_name='frauddetection.FraudDetectionService.GetFraudDetection',
    index=3,
    containing_service=None,
    input_type=_GETFRAUDDETECTIONCOMMAND,
    output_type=fraud__detection__common__pb2._FRAUDDETECTIONSTATE,
    serialized_options=b'\202\323\344\223\002 \022\036/fraud-detection/{customer_id}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAUDDETECTIONSERVICE)

DESCRIPTOR.services_by_name['FraudDetectionService'] = _FRAUDDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
